version: "3.8"

services:
  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway_service
    ports:
      - "8081:80"
    environment:
      - APP_ENV=local
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=gateway_db
      - DB_USERNAME=sail
      - DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - app-network

  coach-service:
    build:
      context: ./coach_service
      dockerfile: Dockerfile
    container_name: coach_service
    ports:
      - "8082:80"
    environment:
      - APP_ENV=local
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=order_service_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - app-network

  gateway-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
